// Generated from: features/F-03/F-03-01-005_product-table.feature
import { test } from "playwright-bdd";

test.describe('製品一覧テーブル・ソート・ページング', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
    await And('テストデータが初期化されている'); 
    await And('製品一覧画面が表示されている', null, { page }); 
  });
  
  test('製品一覧テーブルに7列の情報が正しく表示される', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Then, And, page }) => { 
    await Then('製品一覧テーブルの各行にSKUが表示されている', null, { page }); 
    await And('製品一覧テーブルの各行に製品名が表示されている', null, { page }); 
    await And('製品一覧テーブルの各行にカテゴリが表示されている', null, { page }); 
    await And('製品一覧テーブルの各行にメーカーが表示されている', null, { page }); 
    await And('製品一覧テーブルの各行に単価が表示されている', null, { page }); 
    await And('製品一覧テーブルの各行にステータスが表示されている', null, { page }); 
    await And('製品一覧テーブルの各行に在庫数が表示されている', null, { page }); 
  });

  test('単価が通貨フォーマットで表示される', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Then, page }) => { 
    await Then('製品一覧テーブルの単価列が "¥" 付きカンマ区切りで表示されている', null, { page }); 
  });

  test('ステータスが日本語ラベルで表示される', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('ステータスフィルタで "有効" を選択する', null, { page }); 
    await Then('製品一覧テーブルに表示されている全製品のステータスラベルが "有効" である', null, { page }); 
  });

  test('デフォルトで製品名昇順にソートされている', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Then, page }) => { 
    await Then('製品名列に昇順ソートインジケータが表示されている', null, { page }); 
  });

  test('SKU列ヘッダクリックでSKU昇順にソートされる', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('"SKU" 列ヘッダをクリックする', null, { page }); 
    await Then('SKU列に昇順ソートインジケータが表示されている', null, { page }); 
  });

  test('同一列ヘッダ再クリックで降順に切り替わる', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, And, page }) => { 
    await When('"SKU" 列ヘッダをクリックする', null, { page }); 
    await And('"SKU" 列ヘッダをクリックする', null, { page }); 
    await Then('SKU列に降順ソートインジケータが表示されている', null, { page }); 
  });

  test.describe('ソート可能列のヘッダクリックでソートが切り替わる', () => {

    test('Example #1', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
      await When('"SKU" 列ヘッダをクリックする', null, { page }); 
      await Then('SKU列にソートインジケータが表示されている', null, { page }); 
    });

    test('Example #2', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
      await When('"製品名" 列ヘッダをクリックする', null, { page }); 
      await Then('製品名列にソートインジケータが表示されている', null, { page }); 
    });

    test('Example #3', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
      await When('"カテゴリ" 列ヘッダをクリックする', null, { page }); 
      await Then('カテゴリ列にソートインジケータが表示されている', null, { page }); 
    });

    test('Example #4', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
      await When('"メーカー" 列ヘッダをクリックする', null, { page }); 
      await Then('メーカー列にソートインジケータが表示されている', null, { page }); 
    });

    test('Example #5', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
      await When('"単価" 列ヘッダをクリックする', null, { page }); 
      await Then('単価列にソートインジケータが表示されている', null, { page }); 
    });

    test('Example #6', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
      await When('"ステータス" 列ヘッダをクリックする', null, { page }); 
      await Then('ステータス列にソートインジケータが表示されている', null, { page }); 
    });

  });

  test('初期表示で件数情報が正しく表示される', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Then, And, page }) => { 
    await Then('ページ件数情報に "100件中 1〜20件を表示" と表示されている', null, { page }); 
    await And('ページ番号 "1" がアクティブである', null, { page }); 
  });

  test('ページ番号2クリックで2ページ目が表示される', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, And, page }) => { 
    await When('ページ番号 "2" をクリックする', null, { page }); 
    await Then('製品一覧テーブルに20件の製品が表示されている', null, { page }); 
    await And('ページ件数情報に "100件中 21〜40件を表示" と表示されている', null, { page }); 
    await And('ページ番号 "2" がアクティブである', null, { page }); 
  });

  test('最終ページで次ページ・末尾ボタンが無効になる', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, And, page }) => { 
    await When('ページ番号 "5" をクリックする', null, { page }); 
    await Then('ページ件数情報に "100件中 81〜100件を表示" と表示されている', null, { page }); 
    await And('次ページボタンが無効である', null, { page }); 
    await And('末尾ページボタンが無効である', null, { page }); 
  });

  test('先頭ページで前ページ・先頭ボタンが無効になる', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Then, And, page }) => { 
    await Then('前ページボタンが無効である', null, { page }); 
    await And('先頭ページボタンが無効である', null, { page }); 
  });

  test('先頭ページボタンで1ページ目に戻る', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Given, When, Then, And, page }) => { 
    await Given('ページ番号 "3" を表示している', null, { page }); 
    await When('先頭ページボタンをクリックする', null, { page }); 
    await Then('ページ番号 "1" がアクティブである', null, { page }); 
    await And('ページ件数情報に "100件中 1〜20件を表示" と表示されている', null, { page }); 
  });

  test('次ページボタンで次のページに遷移する', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('次ページボタンをクリックする', null, { page }); 
    await Then('ページ番号 "2" がアクティブである', null, { page }); 
  });

  test('前ページボタンで前のページに遷移する', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ Given, When, Then, page }) => { 
    await Given('ページ番号 "3" を表示している', null, { page }); 
    await When('前ページボタンをクリックする', null, { page }); 
    await Then('ページ番号 "2" がアクティブである', null, { page }); 
  });

  test('末尾ページボタンで最終ページに遷移する', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('末尾ページボタンをクリックする', null, { page }); 
    await Then('ページ番号 "5" がアクティブである', null, { page }); 
  });

  test('製品行クリックで製品詳細画面に遷移する', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('製品一覧テーブルの任意の製品行をクリックする', null, { page }); 
    await Then('製品詳細画面が表示される', null, { page }); 
  });

  test('フィルタ結果が20件以下の場合ページングが1ページのみになる', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@データ状態'] }, async ({ When, Then, page }) => { 
    await When('カテゴリフィルタで製品数が20件以下のカテゴリを選択する', null, { page }); 
    await Then('ページ番号ボタンが "1" のみ表示されている', null, { page }); 
  });

  test.describe('全ロールのユーザーが製品一覧を閲覧できる', () => {

    test('Example #1', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@権限'] }, async ({ Given, When, Then, page }) => { 
      await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
      await When('製品一覧画面にアクセスする', null, { page }); 
      await Then('製品一覧テーブルに20件の製品が表示されている', null, { page }); 
    });

    test('Example #2', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@権限'] }, async ({ Given, When, Then, page }) => { 
      await Given('テスト用ユーザー "MANAGER" でログインしている', null, { page }); 
      await When('製品一覧画面にアクセスする', null, { page }); 
      await Then('製品一覧テーブルに20件の製品が表示されている', null, { page }); 
    });

    test('Example #3', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@権限'] }, async ({ Given, When, Then, page }) => { 
      await Given('テスト用ユーザー "BUYER" でログインしている', null, { page }); 
      await When('製品一覧画面にアクセスする', null, { page }); 
      await Then('製品一覧テーブルに20件の製品が表示されている', null, { page }); 
    });

    test('Example #4', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@権限'] }, async ({ Given, When, Then, page }) => { 
      await Given('テスト用ユーザー "WAREHOUSE_STAFF" でログインしている', null, { page }); 
      await When('製品一覧画面にアクセスする', null, { page }); 
      await Then('製品一覧テーブルに20件の製品が表示されている', null, { page }); 
    });

    test('Example #5', { tag: ['@F-03-01-005', '@F-03-01-006', '@F-03-01-007', '@F-03-01-012', '@UC-008', '@権限'] }, async ({ Given, When, Then, page }) => { 
      await Given('テスト用ユーザー "VIEWER" でログインしている', null, { page }); 
      await When('製品一覧画面にアクセスする', null, { page }); 
      await Then('製品一覧テーブルに20件の製品が表示されている', null, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/F-03/F-03-01-005_product-table.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":13,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルの各行にSKUが表示されている","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And 製品一覧テーブルの各行に製品名が表示されている","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And 製品一覧テーブルの各行にカテゴリが表示されている","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"And 製品一覧テーブルの各行にメーカーが表示されている","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":18,"keywordType":"Outcome","textWithKeyword":"And 製品一覧テーブルの各行に単価が表示されている","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"And 製品一覧テーブルの各行にステータスが表示されている","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"And 製品一覧テーブルの各行に在庫数が表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":22,"pickleLine":23,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルの単価列が \"¥\" 付きカンマ区切りで表示されている","stepMatchArguments":[{"group":{"start":14,"value":"\"¥\"","children":[{"start":15,"value":"¥","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":26,"pickleLine":27,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When ステータスフィルタで \"有効\" を選択する","stepMatchArguments":[{"group":{"start":11,"value":"\"有効\"","children":[{"start":12,"value":"有効","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに表示されている全製品のステータスラベルが \"有効\" である","stepMatchArguments":[{"group":{"start":30,"value":"\"有効\"","children":[{"start":31,"value":"有効","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":31,"pickleLine":34,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 製品名列に昇順ソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":35,"pickleLine":38,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When \"SKU\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"SKU\"","children":[{"start":1,"value":"SKU","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then SKU列に昇順ソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":40,"pickleLine":43,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When \"SKU\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"SKU\"","children":[{"start":1,"value":"SKU","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"And \"SKU\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"SKU\"","children":[{"start":1,"value":"SKU","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then SKU列に降順ソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":55,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":49,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When \"SKU\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"SKU\"","children":[{"start":1,"value":"SKU","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then SKU列にソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":53,"pickleLine":56,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When \"製品名\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"製品名\"","children":[{"start":1,"value":"製品名","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then 製品名列にソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":58,"pickleLine":57,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When \"カテゴリ\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ\"","children":[{"start":1,"value":"カテゴリ","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then カテゴリ列にソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":58,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When \"メーカー\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"メーカー\"","children":[{"start":1,"value":"メーカー","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then メーカー列にソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":68,"pickleLine":59,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When \"単価\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"単価\"","children":[{"start":1,"value":"単価","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then 単価列にソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":73,"pickleLine":60,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When \"ステータス\" 列ヘッダをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"ステータス\"","children":[{"start":1,"value":"ステータス","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then ステータス列にソートインジケータが表示されている","stepMatchArguments":[]}]},
  {"pwTestLine":80,"pickleLine":65,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then ページ件数情報に \"100件中 1〜20件を表示\" と表示されている","stepMatchArguments":[{"group":{"start":9,"value":"\"100件中 1〜20件を表示\"","children":[{"start":10,"value":"100件中 1〜20件を表示","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"And ページ番号 \"1\" がアクティブである","stepMatchArguments":[{"group":{"start":6,"value":"\"1\"","children":[{"start":7,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":85,"pickleLine":70,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When ページ番号 \"2\" をクリックする","stepMatchArguments":[{"group":{"start":6,"value":"\"2\"","children":[{"start":7,"value":"2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに20件の製品が表示されている","stepMatchArguments":[{"group":{"start":9,"value":"20","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":88,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"And ページ件数情報に \"100件中 21〜40件を表示\" と表示されている","stepMatchArguments":[{"group":{"start":9,"value":"\"100件中 21〜40件を表示\"","children":[{"start":10,"value":"100件中 21〜40件を表示","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"And ページ番号 \"2\" がアクティブである","stepMatchArguments":[{"group":{"start":6,"value":"\"2\"","children":[{"start":7,"value":"2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":92,"pickleLine":77,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":93,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When ページ番号 \"5\" をクリックする","stepMatchArguments":[{"group":{"start":6,"value":"\"5\"","children":[{"start":7,"value":"5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then ページ件数情報に \"100件中 81〜100件を表示\" と表示されている","stepMatchArguments":[{"group":{"start":9,"value":"\"100件中 81〜100件を表示\"","children":[{"start":10,"value":"100件中 81〜100件を表示","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":95,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"And 次ページボタンが無効である","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"And 末尾ページボタンが無効である","stepMatchArguments":[]}]},
  {"pwTestLine":99,"pickleLine":84,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":100,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then 前ページボタンが無効である","stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"And 先頭ページボタンが無効である","stepMatchArguments":[]}]},
  {"pwTestLine":104,"pickleLine":89,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"Given ページ番号 \"3\" を表示している","stepMatchArguments":[{"group":{"start":6,"value":"\"3\"","children":[{"start":7,"value":"3","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When 先頭ページボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then ページ番号 \"1\" がアクティブである","stepMatchArguments":[{"group":{"start":6,"value":"\"1\"","children":[{"start":7,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":93,"keywordType":"Outcome","textWithKeyword":"And ページ件数情報に \"100件中 1〜20件を表示\" と表示されている","stepMatchArguments":[{"group":{"start":9,"value":"\"100件中 1〜20件を表示\"","children":[{"start":10,"value":"100件中 1〜20件を表示","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":111,"pickleLine":96,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":112,"gherkinStepLine":97,"keywordType":"Action","textWithKeyword":"When 次ページボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":113,"gherkinStepLine":98,"keywordType":"Outcome","textWithKeyword":"Then ページ番号 \"2\" がアクティブである","stepMatchArguments":[{"group":{"start":6,"value":"\"2\"","children":[{"start":7,"value":"2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":116,"pickleLine":101,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":117,"gherkinStepLine":102,"keywordType":"Context","textWithKeyword":"Given ページ番号 \"3\" を表示している","stepMatchArguments":[{"group":{"start":6,"value":"\"3\"","children":[{"start":7,"value":"3","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":103,"keywordType":"Action","textWithKeyword":"When 前ページボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":104,"keywordType":"Outcome","textWithKeyword":"Then ページ番号 \"2\" がアクティブである","stepMatchArguments":[{"group":{"start":6,"value":"\"2\"","children":[{"start":7,"value":"2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":122,"pickleLine":107,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":108,"keywordType":"Action","textWithKeyword":"When 末尾ページボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":124,"gherkinStepLine":109,"keywordType":"Outcome","textWithKeyword":"Then ページ番号 \"5\" がアクティブである","stepMatchArguments":[{"group":{"start":6,"value":"\"5\"","children":[{"start":7,"value":"5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":127,"pickleLine":114,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":128,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"When 製品一覧テーブルの任意の製品行をクリックする","stepMatchArguments":[]},{"pwStepLine":129,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then 製品詳細画面が表示される","stepMatchArguments":[]}]},
  {"pwTestLine":132,"pickleLine":121,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@データ状態"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":122,"keywordType":"Action","textWithKeyword":"When カテゴリフィルタで製品数が20件以下のカテゴリを選択する","stepMatchArguments":[]},{"pwStepLine":134,"gherkinStepLine":123,"keywordType":"Outcome","textWithKeyword":"Then ページ番号ボタンが \"1\" のみ表示されている","stepMatchArguments":[{"group":{"start":10,"value":"\"1\"","children":[{"start":11,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":139,"pickleLine":135,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":140,"gherkinStepLine":129,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":141,"gherkinStepLine":130,"keywordType":"Action","textWithKeyword":"When 製品一覧画面にアクセスする","stepMatchArguments":[]},{"pwStepLine":142,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに20件の製品が表示されている","stepMatchArguments":[{"group":{"start":9,"value":"20","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":145,"pickleLine":136,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":129,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"MANAGER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"MANAGER\"","children":[{"start":10,"value":"MANAGER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":147,"gherkinStepLine":130,"keywordType":"Action","textWithKeyword":"When 製品一覧画面にアクセスする","stepMatchArguments":[]},{"pwStepLine":148,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに20件の製品が表示されている","stepMatchArguments":[{"group":{"start":9,"value":"20","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":151,"pickleLine":137,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":152,"gherkinStepLine":129,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"BUYER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"BUYER\"","children":[{"start":10,"value":"BUYER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":153,"gherkinStepLine":130,"keywordType":"Action","textWithKeyword":"When 製品一覧画面にアクセスする","stepMatchArguments":[]},{"pwStepLine":154,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに20件の製品が表示されている","stepMatchArguments":[{"group":{"start":9,"value":"20","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":157,"pickleLine":138,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":158,"gherkinStepLine":129,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"WAREHOUSE_STAFF\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"WAREHOUSE_STAFF\"","children":[{"start":10,"value":"WAREHOUSE_STAFF","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":159,"gherkinStepLine":130,"keywordType":"Action","textWithKeyword":"When 製品一覧画面にアクセスする","stepMatchArguments":[]},{"pwStepLine":160,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに20件の製品が表示されている","stepMatchArguments":[{"group":{"start":9,"value":"20","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":163,"pickleLine":139,"tags":["@F-03-01-005","@F-03-01-006","@F-03-01-007","@F-03-01-012","@UC-008","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":164,"gherkinStepLine":129,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"VIEWER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"VIEWER\"","children":[{"start":10,"value":"VIEWER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":165,"gherkinStepLine":130,"keywordType":"Action","textWithKeyword":"When 製品一覧画面にアクセスする","stepMatchArguments":[]},{"pwStepLine":166,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧テーブルに20件の製品が表示されている","stepMatchArguments":[{"group":{"start":9,"value":"20","children":[]},"parameterTypeName":"int"}]}]},
]; // bdd-data-end