// Generated from: features/F-03/F-03-01-008_navigation.feature
import { test } from "playwright-bdd";

test.describe('製品一覧画面のナビゲーションボタン', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
    await And('テストデータが初期化されている'); 
    await And('製品一覧画面が表示されている', null, { page }); 
  });
  
  test('カテゴリ管理ボタンが表示されている', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@正常系'] }, async ({ Then, page }) => { 
    await Then('"カテゴリ管理" ボタンが表示されている', null, { page }); 
  });

  test('カテゴリ管理ボタンクリックでカテゴリ管理画面に遷移する', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('"カテゴリ管理" ボタンをクリックする', null, { page }); 
    await Then('カテゴリ管理画面が表示される', null, { page }); 
  });

  test('バンドル管理ボタンが表示されている', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@正常系'] }, async ({ Then, page }) => { 
    await Then('"バンドル管理" ボタンが表示されている', null, { page }); 
  });

  test('バンドル管理ボタンクリックでバンドル管理画面に遷移する', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('"バンドル管理" ボタンをクリックする', null, { page }); 
    await Then('バンドル管理画面が表示される', null, { page }); 
  });

  test('新規登録ボタンが表示されている', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@正常系'] }, async ({ Then, page }) => { 
    await Then('"新規登録" ボタンが表示されている', null, { page }); 
  });

  test('新規登録ボタンクリックで製品登録画面に遷移する', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('"新規登録" ボタンをクリックする', null, { page }); 
    await Then('製品新規登録画面が表示される', null, { page }); 
  });

  test.describe('全ロールのユーザーがナビゲーションボタンを利用できる', () => {

    test('Example #1', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@権限'] }, async ({ Given, Then, And, page }) => { 
      await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
      await And('製品一覧画面が表示されている', null, { page }); 
      await Then('"カテゴリ管理" ボタンが表示されている', null, { page }); 
      await And('"バンドル管理" ボタンが表示されている', null, { page }); 
      await And('"新規登録" ボタンが表示されている', null, { page }); 
    });

    test('Example #2', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@権限'] }, async ({ Given, Then, And, page }) => { 
      await Given('テスト用ユーザー "MANAGER" でログインしている', null, { page }); 
      await And('製品一覧画面が表示されている', null, { page }); 
      await Then('"カテゴリ管理" ボタンが表示されている', null, { page }); 
      await And('"バンドル管理" ボタンが表示されている', null, { page }); 
      await And('"新規登録" ボタンが表示されている', null, { page }); 
    });

    test('Example #3', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@権限'] }, async ({ Given, Then, And, page }) => { 
      await Given('テスト用ユーザー "BUYER" でログインしている', null, { page }); 
      await And('製品一覧画面が表示されている', null, { page }); 
      await Then('"カテゴリ管理" ボタンが表示されている', null, { page }); 
      await And('"バンドル管理" ボタンが表示されている', null, { page }); 
      await And('"新規登録" ボタンが表示されている', null, { page }); 
    });

    test('Example #4', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@権限'] }, async ({ Given, Then, And, page }) => { 
      await Given('テスト用ユーザー "WAREHOUSE_STAFF" でログインしている', null, { page }); 
      await And('製品一覧画面が表示されている', null, { page }); 
      await Then('"カテゴリ管理" ボタンが表示されている', null, { page }); 
      await And('"バンドル管理" ボタンが表示されている', null, { page }); 
      await And('"新規登録" ボタンが表示されている', null, { page }); 
    });

    test('Example #5', { tag: ['@F-03-01-008', '@F-03-01-009', '@F-03-01-011', '@権限'] }, async ({ Given, Then, And, page }) => { 
      await Given('テスト用ユーザー "VIEWER" でログインしている', null, { page }); 
      await And('製品一覧画面が表示されている', null, { page }); 
      await Then('"カテゴリ管理" ボタンが表示されている', null, { page }); 
      await And('"バンドル管理" ボタンが表示されている', null, { page }); 
      await And('"新規登録" ボタンが表示されている', null, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/F-03/F-03-01-008_navigation.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":13,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then \"カテゴリ管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":16,"pickleLine":17,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When \"カテゴリ管理\" ボタンをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then カテゴリ管理画面が表示される","stepMatchArguments":[]}]},
  {"pwTestLine":21,"pickleLine":22,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then \"バンドル管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":25,"pickleLine":26,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When \"バンドル管理\" ボタンをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"Then バンドル管理画面が表示される","stepMatchArguments":[]}]},
  {"pwTestLine":30,"pickleLine":31,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then \"新規登録\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":34,"pickleLine":35,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"When \"新規登録\" ボタンをクリックする","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then 製品新規登録画面が表示される","stepMatchArguments":[]}]},
  {"pwTestLine":41,"pickleLine":51,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then \"カテゴリ管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And \"バンドル管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"And \"新規登録\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":52,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"MANAGER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"MANAGER\"","children":[{"start":10,"value":"MANAGER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then \"カテゴリ管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And \"バンドル管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"And \"新規登録\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":57,"pickleLine":53,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"BUYER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"BUYER\"","children":[{"start":10,"value":"BUYER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":59,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then \"カテゴリ管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And \"バンドル管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"And \"新規登録\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":65,"pickleLine":54,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"WAREHOUSE_STAFF\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"WAREHOUSE_STAFF\"","children":[{"start":10,"value":"WAREHOUSE_STAFF","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then \"カテゴリ管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And \"バンドル管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"And \"新規登録\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":73,"pickleLine":55,"tags":["@F-03-01-008","@F-03-01-009","@F-03-01-011","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"VIEWER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"VIEWER\"","children":[{"start":10,"value":"VIEWER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And 製品一覧画面が表示されている","stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then \"カテゴリ管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"カテゴリ管理\"","children":[{"start":1,"value":"カテゴリ管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And \"バンドル管理\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"バンドル管理\"","children":[{"start":1,"value":"バンドル管理","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"And \"新規登録\" ボタンが表示されている","stepMatchArguments":[{"group":{"start":0,"value":"\"新規登録\"","children":[{"start":1,"value":"新規登録","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end