// Generated from: features/F-03/F-03-02-002_navigation.feature
import { test } from "playwright-bdd";

test.describe('製品詳細画面のナビゲーションボタン', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
    await And('テストデータが初期化されている'); 
    await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
  });
  
  test('「一覧に戻る」ボタンクリックで製品一覧画面に遷移する', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('「一覧に戻る」ボタンをクリックする', null, { page }); 
    await Then('製品一覧画面に遷移している', null, { page }); 
  });

  test('「編集」ボタンクリックで製品編集画面に遷移する', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@正常系'] }, async ({ When, Then, page }) => { 
    await When('「編集」ボタンをクリックする', null, { page }); 
    await Then('製品編集画面に遷移している', null, { page }); 
  });

  test.describe('全ロールのユーザーが一覧に戻るボタンを操作できる', () => {

    test('Example #1', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「一覧に戻る」ボタンをクリックする', null, { page }); 
      await Then('製品一覧画面に遷移している', null, { page }); 
    });

    test('Example #2', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "MANAGER" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「一覧に戻る」ボタンをクリックする', null, { page }); 
      await Then('製品一覧画面に遷移している', null, { page }); 
    });

    test('Example #3', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "BUYER" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「一覧に戻る」ボタンをクリックする', null, { page }); 
      await Then('製品一覧画面に遷移している', null, { page }); 
    });

    test('Example #4', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "WAREHOUSE_STAFF" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「一覧に戻る」ボタンをクリックする', null, { page }); 
      await Then('製品一覧画面に遷移している', null, { page }); 
    });

    test('Example #5', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "VIEWER" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「一覧に戻る」ボタンをクリックする', null, { page }); 
      await Then('製品一覧画面に遷移している', null, { page }); 
    });

  });

  test.describe('全ロールのユーザーが編集ボタンを操作できる', () => {

    test('Example #1', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "ADMIN" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「編集」ボタンをクリックする', null, { page }); 
      await Then('製品編集画面に遷移している', null, { page }); 
    });

    test('Example #2', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "MANAGER" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「編集」ボタンをクリックする', null, { page }); 
      await Then('製品編集画面に遷移している', null, { page }); 
    });

    test('Example #3', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "BUYER" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「編集」ボタンをクリックする', null, { page }); 
      await Then('製品編集画面に遷移している', null, { page }); 
    });

    test('Example #4', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "WAREHOUSE_STAFF" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「編集」ボタンをクリックする', null, { page }); 
      await Then('製品編集画面に遷移している', null, { page }); 
    });

    test('Example #5', { tag: ['@F-03-02-002', '@F-03-02-003', '@UC-010', '@権限'] }, async ({ Given, When, Then, And, page }) => { 
      await Given('テスト用ユーザー "VIEWER" でログインしている', null, { page }); 
      await And('製品ID "1" の製品詳細画面を表示している', null, { page }); 
      await When('「編集」ボタンをクリックする', null, { page }); 
      await Then('製品編集画面に遷移している', null, { page }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/F-03/F-03-02-002_navigation.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":13,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"When 「一覧に戻る」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":17,"pickleLine":18,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@正常系"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When 「編集」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then 製品編集画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":33,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When 「一覧に戻る」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":31,"pickleLine":34,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"MANAGER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"MANAGER\"","children":[{"start":10,"value":"MANAGER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When 「一覧に戻る」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":38,"pickleLine":35,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"BUYER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"BUYER\"","children":[{"start":10,"value":"BUYER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When 「一覧に戻る」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":45,"pickleLine":36,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"WAREHOUSE_STAFF\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"WAREHOUSE_STAFF\"","children":[{"start":10,"value":"WAREHOUSE_STAFF","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When 「一覧に戻る」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":49,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":52,"pickleLine":37,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"VIEWER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"VIEWER\"","children":[{"start":10,"value":"VIEWER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When 「一覧に戻る」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then 製品一覧画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":48,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When 「編集」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then 製品編集画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":70,"pickleLine":49,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"MANAGER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"MANAGER\"","children":[{"start":10,"value":"MANAGER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When 「編集」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then 製品編集画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":77,"pickleLine":50,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"BUYER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"BUYER\"","children":[{"start":10,"value":"BUYER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":80,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When 「編集」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then 製品編集画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":84,"pickleLine":51,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"WAREHOUSE_STAFF\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"WAREHOUSE_STAFF\"","children":[{"start":10,"value":"WAREHOUSE_STAFF","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When 「編集」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then 製品編集画面に遷移している","stepMatchArguments":[]}]},
  {"pwTestLine":91,"pickleLine":52,"tags":["@F-03-02-002","@F-03-02-003","@UC-010","@権限"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"ADMIN\" でログインしている","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"ADMIN\"","children":[{"start":10,"value":"ADMIN","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And テストデータが初期化されている","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","isBg":true,"stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given テスト用ユーザー \"VIEWER\" でログインしている","stepMatchArguments":[{"group":{"start":9,"value":"\"VIEWER\"","children":[{"start":10,"value":"VIEWER","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"And 製品ID \"1\" の製品詳細画面を表示している","stepMatchArguments":[{"group":{"start":5,"value":"\"1\"","children":[{"start":6,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When 「編集」ボタンをクリックする","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then 製品編集画面に遷移している","stepMatchArguments":[]}]},
]; // bdd-data-end