quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5433/proquip}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:proquip}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:proquip}

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=filesystem:/deployments/db/migration,classpath:db/migration

quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

quarkus.http.port=8080
